title: RuralKG Dataset for Substance Abuse, Mental Health, and Justice in Rural America

description: This is the documentation site for RuralKG Dataset for Substance Abuse, Mental Health, and Justice in Rural America

url: "https://sail-ua.github.io/leap.github.io/"

remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs

# Sidebar navigation structure
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "Installation"
    url: "/installation"
    nav_order: 2
  - title: "Data Load"
    url: "/data-load"
    nav_order: 3
  - title: "Generate Feature Matrix"
    url: "/generate-feature-matrix"
    nav_order: 4
  - title: "Get Label"
    url: "/get-label"
    nav_order: 5
  - title: "Train Model"
    url: "/train-model"
    nav_order: 6
  - title: "Feature Importance Analysis"
    url: "/feature-importance-analysis"
    nav_order: 7
  - title: "t-SNE Visualization"
    url: "/tsne-visualization"
    nav_order: 8
  - title: "Our Team"
    url: "/our-team"
    nav_order: 9
